language: go

go:
 - 1.12.x

os: linux
dist: xenial

sudo: false

branches:
  only:
  - master

matrix:
  fast_finish: false
  include:
    - env: ENV=unit-tests
      script:
        - cd datastore-translator
        - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
    - env: ENV=integration-tests
      script:
        - cd datastore-translator
        - export DATASTORE_EMULATOR_HOST=127.0.0.1:8081
        - export DATASTORE_EMULATOR_HOST_PATH=127.0.0.1:8081/datastore
        - export DATASTORE_HOST=http://127.0.0.1:8081
        - export DATASTORE_PROJECT_ID=translator-tests
        - go test -v ./... -race -tags=integration

notifications:
  email:
    on_success: change
    on_failure: always

install: true

before_script:
  - ./scripts/run-datastore-emulator.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
