language: go

go:
 - 1.12.x

os: linux
dist: trusty
sudo: false

branches:
  only:
  - master

notifications:
  email:
    on_success: change
    on_failure: always

install: true

script:
  - cd translator
  - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)