language: go

go:
 - 1.12.x

os: linux
dist: trusty
sudo: required

branches:
  only:
  - master

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - cd translator
  - go test -v ./...
