language: go

go:
 - 1.12.x

os: linux
dist: trusty
addons:
  apt:
    packages:
    - google-cloud-sdk

sudo: false

branches:
  only:
  - master

notifications:
  email:
    on_success: change
    on_failure: always

install: true

before_script:
  - gcloud beta emulators datastore start &
  - $(gcloud beta emulators datastore env-init)

script:
  - cd translator
  - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
  - go test -v ./... -race -tags=integration

after_success:
  - bash <(curl -s https://codecov.io/bash)